import sqlite3
import json
from pathlib import Path
import sys
import os
import time
from datetime import datetime

# Ensure project root is in PYTHONPATH
project_root = Path(__file__).resolve().parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

def optimize_databases():
    print("[1] Defragmenting and Optimizing SQLite Databases...")
    db_dir = project_root / "database"
    if not db_dir.exists():
        print("Database directory not found. Skipping.")
        return

    db_files = list(db_dir.rglob("*.db")) + list(db_dir.rglob("*.sqlite"))
    for db_path in db_files:
        try:
            initial_size = db_path.stat().st_size
            print(f"  -> Vacuuming {db_path.name} (Initial Size: {initial_size / (1024*1024):.2f} MB)...")
            
            # Connect and execute VACUUM and apply WAL mode permanently
            conn = sqlite3.connect(db_path)
            conn.execute("PRAGMA journal_mode=WAL;")
            conn.execute("PRAGMA synchronous=NORMAL;")
            conn.execute("VACUUM;")
            conn.commit()
            conn.close()
            
            final_size = db_path.stat().st_size
            saved = initial_size - final_size
            if saved > 0:
                print(f"     ✅ Saved {saved / (1024*1024):.2f} MB!")
            else:
                print(f"     ✅ Already optimal.")
        except Exception as e:
            print(f"     ❌ Failed to optimize {db_path.name}: {e}")

def run_dlm():
    print("\n[2] Running Data Lifecycle Management (DLM)...")
    try:
        from src.utils.data_lifecycle import manage_data_lifecycle
        manage_data_lifecycle()
        print("  ✅ DLM Complete.")
    except Exception as e:
        print(f"  ❌ DLM failed: {e}")

def validate_system():
    print("\n[3] Running System Diagnostics & Healing...")
    try:
        import subprocess
        venv_python = project_root / ".venv" / "Scripts" / "python.exe"
        validate_script = project_root / "src" / "validate_env.py"
        
        if venv_python.exists() and validate_script.exists():
            env = os.environ.copy()
            env["PYTHONPATH"] = str(project_root)
            
            res = subprocess.run(
                [str(venv_python), str(validate_script)],
                env=env,
                capture_output=True,
                text=True
            )
            if res.returncode == 0:
                print("  ✅ Environment is healthy and fully synced.")
            else:
                print("  ⚠️ Diagnostic warnings found:")
                lines = [l for l in res.stdout.strip().split('\n') if l]
                print('\n'.join(lines[-5:]))
        else:
            print("  ❌ Could not locate python or validate script.")
    except Exception as e:
        print(f"  ❌ Validation failed: {e}")

def generate_workspace_status():
    """Write WORKSPACE_STATUS.md — a 20-line dashboard for fast context loading."""
    print("\n[4] Generating WORKSPACE_STATUS.md...")

    pipelines = [
        "energy_price_forecast",
        "cpi_forecast",
        "ex_im_price_forecast",
        "prepared_food_shock",
        "energy_price_forecast_LR",
        "thailand_price_system",
    ]

    def latest_report_mtime(pipeline: str) -> str:
        report_dir = project_root / "report" / pipeline
        if not report_dir.exists():
            return "—"
        files = sorted(report_dir.rglob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)
        if not files:
            return "—"
        return datetime.fromtimestamp(files[0].stat().st_mtime).strftime("%Y-%m-%d")

    # Find loose files in output/ roots
    loose_charts = [f.name for f in (project_root / "output" / "chart").iterdir()
                    if f.is_file()] if (project_root / "output" / "chart").exists() else []
    loose_data   = [f.name for f in (project_root / "output" / "data").iterdir()
                    if f.is_file()] if (project_root / "output" / "data").exists() else []

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Workspace Status",
        f"*Auto-generated by `/maintain` on {now}*",
        "",
        "## Pipeline Reports",
        "",
        "| Pipeline | Last Run |",
        "|---|---|",
    ]
    for p in pipelines:
        lines.append(f"| `{p}` | {latest_report_mtime(p)} |")

    lines += [
        "",
        "## Output Root Clutter",
        "",
        f"- `output/chart/` root: **{len(loose_charts)} loose files**" +
        (f" (e.g. {', '.join(loose_charts[:3])}...)" if loose_charts else " — clean"),
        f"- `output/data/` root: **{len(loose_data)} loose files**" +
        (f" (e.g. {', '.join(loose_data[:3])}...)" if loose_data else " — clean"),
    ]

    if loose_charts or loose_data:
        lines += [
            "",
            "> **Action needed:** Move loose files to `output/chart/projects/[task]/`",
            "> or `output/data/projects/[task]/` to comply with naming rules.",
        ]

    out = project_root / "WORKSPACE_STATUS.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  WORKSPACE_STATUS.md written ({len(lines)} lines).")

def main():
    print("======================================================================")
    print("         NESDC AUTONOMOUS OPTIMIZATION & MAINTENANCE DAEMON")
    print("======================================================================")
    start_time = time.time()

    optimize_databases()
    run_dlm()
    validate_system()
    generate_workspace_status()

    duration = time.time() - start_time
    print("======================================================================")
    print(f"           MAINTENANCE COMPLETE (Duration: {duration:.1f}s)")
    print("======================================================================")

if __name__ == "__main__":
    main()
